### PR TITLE
IMMORTAL: Fix Various GCC Compiler Warnings

### PR DESCRIPTION
**Pull request by digitall**
@Quote58 : These changes resolve the various GCC compiler warnings which currently exist with the immortal engine code. You should look over them and if happy, merge this PR using "rebase" to avoid a merge commit. There are some logical changes which will need analysis or playtest to check that the resulting code is correct. Hope this helps.

### CODE REVIEW

**Comment by digitall** [comment]
For reference, the relevant warnings are:
````
In file included from ./engines/immortal/immortal.h:63,
                 from engines/immortal/detection.cpp:24:
./engines/immortal/utilities.h:85:2: warning: extra ‘;’ [-Wpedantic]
 }; // namespace Util
  ^
./engines/immortal/utilities.h:87:2: warning: extra ‘;’ [-Wpedantic]
 }; // namespace Immortal
  ^
````

**Comment by digitall** [comment]
If those are fixed as per the commit, then compilation dies with:
````
engines/immortal/utilities.cpp:28:6: error: explicit qualification in declaration of ‘void Immortal::Utilities::delay(int)’
 void Immortal::Utilities::delay(int j) {             // Delay is measured in jiffies, which are 56.17ms
      ^~~~~~~~
engines/immortal/utilities.cpp:32:6: error: explicit qualification in declaration of ‘void Immortal::Utilities::delay4(int)’
 void Immortal::Utilities::delay4(int j) {            // Named in source quarterClock for some reason, 1/4 jiffies are 14.04ms
      ^~~~~~~~
engines/immortal/utilities.cpp:36:6: error: explicit qualification in declaration of ‘void Immortal::Utilities::delay8(int)’
 void Immortal::Utilities::delay8(int j) {            // 1/8 jiffies are 7.02ms
      ^~~~~~~~
engines/immortal/utilities.cpp:40:6: error: explicit qualification in declaration of ‘bool Immortal::Utilities::inside(int, int, int, int, int)’
 bool Immortal::Utilities::inside(int x1, int y1, int a, int x2, int y2) {
      ^~~~~~~~
engines/immortal/utilities.cpp:43:6: error: explicit qualification in declaration of ‘bool Immortal::Utilities::insideRect(int, int, int)’
 bool Immortal::Utilities::insideRect(int x, int y, int r) {
      ^~~~~~~~
engines/immortal/utilities.cpp:47:6: error: explicit qualification in declaration of ‘void Immortal::Utilities::addSprite(Immortal::Sprite*, uint16, uint16, int, Immortal::DataSprite*, int, uint16, uint16, uint16)’
 void Immortal::Utilities::addSprite(Sprite *sprites, uint16 vpX, uint16 vpY, int num, DataSprite *d, int img, uint16 x, uint16 y, uint16 p) {
      ^~~~~~~~
engines/immortal/utilities.cpp:77:2: warning: extra ‘;’ [-Wpedantic]
 }; // namespace Utilities
  ^
engines/immortal/utilities.cpp:79:2: warning: extra ‘;’ [-Wpedantic]
 }; // namespace Immortal
  ^
make: *** [Makefile.common:172: engines/immortal/utilities.o] Error 1
````

This is due to the redundant / invalid extra qualifications of the classes for the delay methods...

**Comment by digitall** [comment]
If these are fixed, then the build compiles and links, but with the following warnings which are fixed by my changes:
````
engines/immortal/disk.cpp: In member function ‘void Immortal::ProDOSDisk::searchDirectory(Immortal::ProDOSDisk::DirHeader*, uint16, uint16, Common::String)’:
engines/immortal/disk.cpp:276:55: warning: parameter ‘p’ set but not used [-Wunused-but-set-parameter]
 void ProDOSDisk::searchDirectory(DirHeader *h, uint16 p, uint16 n, Common::String path) {
                                                ~~~~~~~^
engines/immortal/kernal.cpp: In member function ‘void Immortal::ImmortalEngine::fade(uint16*, int, int)’:
engines/immortal/kernal.cpp:854:16: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  while ((count >= 0) && (count <= 256)) {
          ~~~~~~^~~~
engines/immortal/kernal.cpp: In member function ‘void Immortal::ImmortalEngine::fixPause()’:
engines/immortal/kernal.cpp:961:4: warning: this statement may fall through [-Wimplicit-fallthrough=]
    if (_themePaused) {
    ^~
engines/immortal/kernal.cpp:965:3: note: here
   default:
   ^~~~~~~
engines/immortal/kernal.cpp:973:4: warning: this statement may fall through [-Wimplicit-fallthrough=]
    if (_themePaused) {
    ^~
engines/immortal/kernal.cpp:977:3: note: here
   default:
   ^~~~~~~
engines/immortal/logic.cpp:52:2: warning: multi-line comment [-Wcomment]
  //monstInit();  <-- room.initMonsters()  \
  ^
engines/immortal/logic.cpp: In member function ‘int Immortal::ImmortalEngine::keyOrButton()’:
engines/immortal/logic.cpp:174:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
     button = _pressedAction;
     ~~~~~~~^~~~~~~~~~~~~~~~
engines/immortal/logic.cpp:175:4: note: here
    case kActionFire:
    ^~~~
engines/immortal/logic.cpp: In member function ‘void Immortal::ImmortalEngine::makeCertificate()’:
engines/immortal/logic.cpp:445:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
     _certificate[kCertInvLo] |= 4;
     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
engines/immortal/logic.cpp:448:3: note: here
   case 3:
   ^~~~
engines/immortal/logic.cpp:450:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
     _certificate[kCertInvLo] |= 1;
     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
engines/immortal/logic.cpp:453:3: note: here
   case 4:
   ^~~~
engines/immortal/logic.cpp:455:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
     _certificate[kCertInvLo] |= 2;
     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
engines/immortal/logic.cpp:458:3: note: here
   case 7:
   ^~~~
engines/immortal/logic.cpp:468:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
     _certificate[kCertInvLo] |= 4;
     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
engines/immortal/logic.cpp:471:3: note: here
   default:
   ^~~~~~~
engines/immortal/level.cpp: In member function ‘void Immortal::ImmortalEngine::levelLoadFile(int)’:
engines/immortal/level.cpp:75:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SDoor>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int d = 0; d < _stories[l]._doors.size(); d++) {
                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/immortal/level.cpp:79:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SRoom>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int r = 0; r < _stories[l]._rooms.size(); r++) {
                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/immortal/level.cpp:84:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SFlame>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
    for (int f = 0; f < _stories[l]._flames[r].size(); f++) {
                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/immortal/level.cpp:95:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SObj>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
    for (int o = 0; o < _stories[l]._objects[r].size(); o++) {
                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/immortal/level.cpp:101:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SMonster>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
    for (int m = 0; m < _stories[l]._monsters[r].size(); m++) {
                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/immortal/story.cpp: In member function ‘void Immortal::ImmortalEngine::initStoryDynamic()’:
engines/immortal/story.cpp:82:20: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘512’ to ‘0’ [-Woverflow]
  uint8 univRoomX = 512;
                    ^~~
engines/immortal/story.cpp:83:20: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘416’ to ‘160’ [-Woverflow]
  uint8 univRoomY = 416;
                    ^~~
engines/immortal/story.cpp:97:35: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘384’ to ‘128’ [-Woverflow]
  Common::Array<SRoom> rooms{SRoom(384, 256, kRoomFlag0), SRoom(512, 64, kRoomFlag0),
                                   ^~~
engines/immortal/story.cpp:97:40: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘256’ to ‘0’ [-Woverflow]
  Common::Array<SRoom> rooms{SRoom(384, 256, kRoomFlag0), SRoom(512, 64, kRoomFlag0),
                                        ^~~
engines/immortal/story.cpp:97:64: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘512’ to ‘0’ [-Woverflow]
  Common::Array<SRoom> rooms{SRoom(384, 256, kRoomFlag0), SRoom(512, 64, kRoomFlag0),
                                                                ^~~
engines/immortal/story.cpp:98:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘640’ to ‘128’ [-Woverflow]
           SRoom(640, 160, kRoomFlag0), SRoom(768, 224, kRoomFlag0),
                 ^~~
engines/immortal/story.cpp:98:46: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘768’ to ‘0’ [-Woverflow]
           SRoom(640, 160, kRoomFlag0), SRoom(768, 224, kRoomFlag0),
                                              ^~~
engines/immortal/story.cpp:99:58: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘960’ to ‘192’ [-Woverflow]
           SRoom(univRoomX, univRoomY, kRoomFlag0), SRoom(960, 512, kRoomFlag0),
                                                          ^~~
engines/immortal/story.cpp:99:63: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘512’ to ‘0’ [-Woverflow]
           SRoom(univRoomX, univRoomY, kRoomFlag0), SRoom(960, 512, kRoomFlag0),
                                                               ^~~
engines/immortal/story.cpp:100:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1024’ to ‘0’ [-Woverflow]
           SRoom(1024, 352, kRoomFlag0), SRoom(896, 64, kRoomFlag0)};
                 ^~~~
engines/immortal/story.cpp:100:23: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘352’ to ‘96’ [-Woverflow]
           SRoom(1024, 352, kRoomFlag0), SRoom(896, 64, kRoomFlag0)};
                       ^~~
engines/immortal/story.cpp:100:47: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘896’ to ‘128’ [-Woverflow]
           SRoom(1024, 352, kRoomFlag0), SRoom(896, 64, kRoomFlag0)};
                                               ^~~
engines/immortal/story.cpp:105:38: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘704’ to ‘192’ [-Woverflow]
  Common::Array<SDoor> doors{SDoor(0, 704, 224, 0, 2, false), SDoor(1, 576, 352, 4, 0, true),
                                      ^~~
engines/immortal/story.cpp:105:71: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘576’ to ‘64’ [-Woverflow]
  Common::Array<SDoor> doors{SDoor(0, 704, 224, 0, 2, false), SDoor(1, 576, 352, 4, 0, true),
                                                                       ^~~
engines/immortal/story.cpp:105:76: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘352’ to ‘96’ [-Woverflow]
  Common::Array<SDoor> doors{SDoor(0, 704, 224, 0, 2, false), SDoor(1, 576, 352, 4, 0, true),
                                                                            ^~~
engines/immortal/story.cpp:106:22: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘704’ to ‘192’ [-Woverflow]
             SDoor(1, 704, 96,  2, 1, false), SDoor(1, 960, 128, 7, 2, false),
                      ^~~
engines/immortal/story.cpp:106:55: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘960’ to ‘192’ [-Woverflow]
             SDoor(1, 704, 96,  2, 1, false), SDoor(1, 960, 128, 7, 2, false),
                                                       ^~~
engines/immortal/story.cpp:107:22: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1088’ to ‘64’ [-Woverflow]
             SDoor(1, 1088,160, 3, 7, false), SDoor(1, 1088,320, 6, 3, false),
                      ^~~~
engines/immortal/story.cpp:107:55: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1088’ to ‘64’ [-Woverflow]
             SDoor(1, 1088,160, 3, 7, false), SDoor(1, 1088,320, 6, 3, false),
                                                       ^~~~
engines/immortal/story.cpp:107:60: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘320’ to ‘64’ [-Woverflow]
             SDoor(1, 1088,160, 3, 7, false), SDoor(1, 1088,320, 6, 3, false),
                                                            ^~~
engines/immortal/story.cpp:108:22: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘896’ to ‘128’ [-Woverflow]
             SDoor(1, 896, 416, 4, 3, false)};
                      ^~~
engines/immortal/story.cpp:108:27: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘416’ to ‘160’ [-Woverflow]
             SDoor(1, 896, 416, 4, 3, false)};
                           ^~~
engines/immortal/story.cpp:114:91: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘288’ to ‘32’ [-Woverflow]
  Common::Array<SFlame> f5{SFlame(512 - 384,   (240 + 32) - 256, kFlameOff),    SFlame(672 - 384, (240 + 32) - 256, kFlameOff)};
                                                                                       ~~~~^~~~~
engines/immortal/story.cpp:116:20: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘544’ to ‘32’ [-Woverflow]
         SFlame(928 - 384,   (48 + 32) - 256,  kFlameNormal)};
                ~~~~^~~~~
engines/immortal/story.cpp:116:39: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘-176’ to ‘80’ [-Woverflow]
         SFlame(928 - 384,   (48 + 32) - 256,  kFlameNormal)};
                             ~~~~~~~~~~^~~~~
engines/immortal/story.cpp:119:21: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘256’ to ‘0’ [-Woverflow]
         SFlame(1024 - 768,  (240 + 32) - 224, kFlameNormal)};
                ~~~~~^~~~~
engines/immortal/story.cpp:138:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘459’ to ‘203’ [-Woverflow]
            SObj(459,  379,  kTypeCoin,     kRingFrame,       kObjNone,                        noTraps),
                 ^~~
engines/immortal/story.cpp:138:23: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘379’ to ‘123’ [-Woverflow]
            SObj(459,  379,  kTypeCoin,     kRingFrame,       kObjNone,                        noTraps),
                       ^~~
engines/immortal/story.cpp:139:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘446’ to ‘190’ [-Woverflow]
            SObj(446,  327,  kTypeWowCharm, kScrollFrame,     kObjNone,                        noTraps)};
                 ^~~
engines/immortal/story.cpp:139:23: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘327’ to ‘71’ [-Woverflow]
            SObj(446,  327,  kTypeWowCharm, kScrollFrame,     kObjNone,                        noTraps)};
                       ^~~
engines/immortal/story.cpp:142:30: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1052’ to ‘28’ [-Woverflow]
  Common::Array<SObj> o9{SObj(1052, 309,  kTypeDead,     kDeadGoblinFrame, kObjIsChest + kObjIsOnGround,    noTraps),
                              ^~~~
engines/immortal/story.cpp:142:36: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘309’ to ‘53’ [-Woverflow]
  Common::Array<SObj> o9{SObj(1052, 309,  kTypeDead,     kDeadGoblinFrame, kObjIsChest + kObjIsOnGround,    noTraps),
                                    ^~~
engines/immortal/story.cpp:144:21: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘464’ to ‘208’ [-Woverflow]
          SObj(128,  464,  kTypeDunRing,  kRingFrame,       0,                               noTraps),
                     ^~~
engines/immortal/story.cpp:145:15: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘837’ to ‘69’ [-Woverflow]
          SObj(837,  421,  kTypeChest,    kChest0Frame,     kObjIsChest,                     noTraps),
               ^~~
engines/immortal/story.cpp:145:21: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘421’ to ‘165’ [-Woverflow]
          SObj(837,  421,  kTypeChest,    kChest0Frame,     kObjIsChest,                     noTraps),
                     ^~~
engines/immortal/story.cpp:147:18: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘597’ to ‘85’ [-Woverflow]
             SObj(597,  457,  kTypeWater,    kVaseFrame,       0,                               noTraps),
                  ^~~
engines/immortal/story.cpp:147:24: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘457’ to ‘201’ [-Woverflow]
             SObj(597,  457,  kTypeWater,    kVaseFrame,       0,                               noTraps),
                        ^~~
engines/immortal/story.cpp:151:30: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1184’ to ‘160’ [-Woverflow]
  Common::Array<SObj> oE{SObj(1184, 426,  kTypePhant,    kAltarFrame,      0,                               noTraps),
                              ^~~~
engines/immortal/story.cpp:151:36: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘426’ to ‘170’ [-Woverflow]
  Common::Array<SObj> oE{SObj(1184, 426,  kTypePhant,    kAltarFrame,      0,                               noTraps),
                                    ^~~
engines/immortal/story.cpp:153:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘671’ to ‘159’ [-Woverflow]
            SObj(671,  461,  kTypeHay,      kNoFrame,         kObjIsRunning + kObjIsInvisible, noTraps),
                 ^~~
engines/immortal/story.cpp:153:23: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘461’ to ‘205’ [-Woverflow]
            SObj(671,  461,  kTypeHay,      kNoFrame,         kObjIsRunning + kObjIsInvisible, noTraps),
                       ^~~
engines/immortal/story.cpp:154:17: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘780’ to ‘12’ [-Woverflow]
            SObj(780,  508,  kTypeBeam,     kNoFrame,         kObjIsRunning + kObjIsInvisible, noTraps)};
                 ^~~
engines/immortal/story.cpp:154:23: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘508’ to ‘252’ [-Woverflow]
            SObj(780,  508,  kTypeBeam,     kNoFrame,         kObjIsRunning + kObjIsInvisible, noTraps)};
                       ^~~
engines/immortal/story.cpp:169:38: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘448’ to ‘192’ [-Woverflow]
  Common::Array<SMonster> m5{SMonster(448,  344, 12, kMonstPlayer,  kMonstA + kMonstIsEngage + kMonstIsTough, progShade,   kShadow),
                                      ^~~
engines/immortal/story.cpp:169:44: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘344’ to ‘88’ [-Woverflow]
  Common::Array<SMonster> m5{SMonster(448,  344, 12, kMonstPlayer,  kMonstA + kMonstIsEngage + kMonstIsTough, progShade,   kShadow),
                                            ^~~
engines/immortal/story.cpp:170:22: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘590’ to ‘78’ [-Woverflow]
             SMonster(590,  381, 12, kMonstPlayer,  kMonstA + kMonstIsEngage + kMonstIsTough, progShade,   kShadow)};
                      ^~~
engines/immortal/story.cpp:170:28: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘381’ to ‘125’ [-Woverflow]
             SMonster(590,  381, 12, kMonstPlayer,  kMonstA + kMonstIsEngage + kMonstIsTough, progShade,   kShadow)};
                            ^~~
engines/immortal/story.cpp:171:38: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1106’ to ‘82’ [-Woverflow]
  Common::Array<SMonster> m9{SMonster(1106, 258, 3,  kMonstPlayer,  kMonstA + kMonstIsEngage,                 progEasy,    kGoblin0),
                                      ^~~~
engines/immortal/story.cpp:171:44: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘258’ to ‘2’ [-Woverflow]
  Common::Array<SMonster> m9{SMonster(1106, 258, 3,  kMonstPlayer,  kMonstA + kMonstIsEngage,                 progEasy,    kGoblin0),
                                            ^~~
engines/immortal/story.cpp:172:20: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘832’ to ‘64’ [-Woverflow]
           SMonster(832,  364, 10, kMonstA,       kMonstB + kMonstIsPoss,                   progUlindor, kUlindor3),
                    ^~~
engines/immortal/story.cpp:172:26: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘364’ to ‘108’ [-Woverflow]
           SMonster(832,  364, 10, kMonstA,       kMonstB + kMonstIsPoss,                   progUlindor, kUlindor3),
                          ^~~
engines/immortal/story.cpp:173:22: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘838’ to ‘70’ [-Woverflow]
             SMonster(838,  370, 15, kMonstPlayer,  kMonstA + kMonstIsEngage,                 progGoblin5, kGoblin7)};
                      ^~~
engines/immortal/story.cpp:173:28: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘370’ to ‘114’ [-Woverflow]
             SMonster(838,  370, 15, kMonstPlayer,  kMonstA + kMonstIsEngage,                 progGoblin5, kGoblin7)};
                            ^~~
engines/immortal/story.cpp:174:38: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1136’ to ‘112’ [-Woverflow]
  Common::Array<SMonster> mE{SMonster(1136, 464, 15, kMonstMonster, kMonstPlayer + kMonstIsEngage,            progPlayer,  kWizard0)};
                                      ^~~~
engines/immortal/story.cpp:174:44: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘464’ to ‘208’ [-Woverflow]
  Common::Array<SMonster> mE{SMonster(1136, 464, 15, kMonstMonster, kMonstPlayer + kMonstIsEngage,            progPlayer,  kWizard0)};
                                            ^~~
engines/immortal/story.cpp:175:38: warning: unsigned conversion from ‘int’ to ‘uint8’ {aka ‘unsigned char’} changes value from ‘1182’ to ‘158’ [-Woverflow]
  Common::Array<SMonster> mF{SMonster(1182, 116, 5,  kMonstPlayer,  kMonstA + kMonstIsEngage,                 progWill2,   kGoblin5)};
                                      ^~~~
engines/immortal/flameSet.cpp: In member function ‘void Immortal::Room::flameDrawAll(uint16, uint16, int)’:
engines/immortal/flameSet.cpp:49:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::Flame>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int i = 0; i < _fset.size(); i++) {
                  ~~^~~~~~~~~~~~~~
engines/immortal/flameSet.cpp: In member function ‘bool Immortal::Room::roomLighted()’:
engines/immortal/flameSet.cpp:63:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::Flame>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int i = 0; i < _fset.size(); i++) {
                  ~~^~~~~~~~~~~~~~
engines/immortal/flameSet.cpp: In member function ‘void Immortal::Room::lightTorch(int, int)’:
engines/immortal/flameSet.cpp:80:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::Flame>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int i = 0; i < _fset.size(); i++) {
                  ~~^~~~~~~~~~~~~~
engines/immortal/flameSet.cpp: In member function ‘void Immortal::Room::flameSetRoom(Common::Array<Immortal::SFlame>)’:
engines/immortal/flameSet.cpp:91:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘Common::Array<Immortal::SFlame>::size_type’ {aka ‘unsigned int’} [-Wsign-compare]
  for (int i = 0; i < allFlames.size(); i++) {
                  ~~^~~~~~~~~~~~~~~~~~
````

**Comment by Quote58** [comment]
Thank you for your interest in my ScummVM branch, I really appreciate it!

The compiler warnings about the extra namespaces were fixed a while ago however, I just haven't updated with a new commit yet (was away for most of last week).

As for the other things in the pull request, I just want to clarify that this is very unfinished code currently, and many things change every time I upload new commits. For example that compiler warning about the unused variables was left there in case I end up needing that information from the disk. If I don't, I will simply remove those variables.

Thanks anyway though! I hadn't noticed the different size for those Story variables, I'll have to look at the source code again and re-evaluate what size they should have been (most likely just uint16 like you wrote though).

**Pull request closed without merging**
